"""Prompt and label sets for ImageNet guidance and SMC evaluations."""

PROMPT_SETS = {
    "guidance_imagenet_eval": [
        ("a photo of a golden retriever catching a frisbee midair", 207),
        ("a photo of a chihuahua peeking out of a bicycle basket", 151),
        ("a photo of a tabby cat under a glass coffee table", 281),
        ("a photo of a zebra seen through tall grass", 340),
        ("a photo of a gorilla holding a bright blue bucket", 366),
        ("a photo of an Indian elephant splashing water with its trunk", 385),
        ("a photo of a red panda curled up on a tree branch", 387),
        ("a photo of an anemone fish hiding behind a coral ledge", 393),
        ("a photo of a pelican landing on a wooden pier", 144),
        ("a photo of a king penguin beside a red sled on the ice", 145),
        ("a photo of a toucan eating a slice of papaya", 96),
        ("a photo of a monarch butterfly resting on a human fingertip", 323),
        ("a photo of a fire truck beside orange traffic cones", 555),
        ("a photo of a garbage truck lifting a green dumpster", 569),
        ("a photo of a jeep crossing a shallow stream", 609),
        ("a photo of a limousine parked beside a row of palm trees", 627),
        ("a photo of an aircraft carrier with several jets on the deck", 403),
        ("a photo of an airliner flying above mountain peaks", 404),
        ("a photo of a lighthouse beside crashing waves", 437),
        ("a photo of a castle behind a stone wall", 483),
        ("a photo of a church beside a graveyard", 497),
        ("a photo of a dishwasher left open with clean plates inside", 534),
        ("a photo of a fountain surrounded by snow", 562),
        ("a photo of a greenhouse filled with hanging plants", 580),
        ("a photo of a mountain tent beside a campfire ring", 672),
        ("a photo of a palace courtyard with an empty stone walkway", 698),
        ("a photo of a suspension bridge above a forested valley", 839),
        ("a photo of a restaurant with empty chairs stacked on tables", 762),
        ("a photo of a refrigerator with fruit on top", 760),
        ("a photo of a sports car covered in autumn leaves", 817),
    ],
    "smc_imagenet_eval": [
        ("a photo of a golden retriever in a backyard", 207),
        ("a photo of a tabby cat sitting on a couch", 281),
        ("a photo of a zebra in a field", 340),
        ("a photo of an elephant at a watering hole", 385),
        ("a photo of a gorilla at the zoo", 366),
        ("a photo of a lion lying in the grass", 291),
        ("a photo of a chihuahua on a leash", 151),
        ("a photo of a seal on a rocky shore", 150),
        ("a photo of a goldfish in an aquarium", 0),
        ("a photo of a great white shark underwater", 2),
        ("a photo of a fire truck parked on a street", 555),
        ("a photo of a garbage truck on a neighborhood road", 569),
        ("a photo of a jeep on a dirt trail", 609),
        ("a photo of a sports car in a parking lot", 817),
        ("a photo of a steam locomotive on railroad tracks", 820),
        ("a photo of a submarine at a naval base", 833),
        ("a photo of an aircraft carrier at sea", 403),
        ("a photo of a rocket on a launch pad", 812),
        ("a photo of a digital clock on a nightstand", 530),
        ("a photo of a limousine on a city street", 627),
        ("a photo of a castle on a hilltop", 483),
        ("a photo of a church with a tall steeple", 497),
        ("a photo of a lighthouse on a cliff", 437),
        ("a photo of a mosque with a dome and minarets", 668),
        ("a photo of a palace with a courtyard", 698),
        ("a photo of a suspension bridge over a river", 718),
        ("a photo of a stone fountain in a town square", 562),
        ("a photo of a greenhouse with plants inside", 580),
        ("a photo of a tent at a campsite", 672),
        ("a photo of a restaurant with tables and chairs", 762),
        ("a photo of bananas on a kitchen counter", 954),
        ("a photo of strawberries in a bowl", 949),
        ("a photo of a pineapple on a table", 953),
        ("a photo of a sandwich on a plate", 933),
        ("a photo of a pizza on a table", 963),
        ("a photo of a hot dog with mustard", 934),
        ("a photo of a plate on a dinner table", 923),
        ("a photo of a wine bottle on a shelf", 907),
        ("a photo of a coffee mug on a desk", 504),
        ("a photo of a mixing bowl on a countertop", 659),
        ("a photo of a wooden chair at a dining table", 765),
        ("a photo of a sofa in a living room", 831),
        ("a photo of a desk in an office", 526),
        ("a photo of a wardrobe in a bedroom", 894),
        ("a photo of a vacuum cleaner on a carpet", 882),
        ("a photo of a toaster on a kitchen counter", 859),
        ("a photo of a refrigerator in a kitchen", 760),
        ("a photo of a washing machine in a laundry room", 897),
        ("a photo of a dishwasher in a kitchen", 534),
        ("a photo of a roll of toilet paper in a bathroom", 999),
    ],
    "guidance_imagenet_visual": [
        ("a high-quality photo of a zebra standing in a supermarket aisle", 340),
        ("a high-quality, high resolution close-up photo of a lighthouse in the middle of a desert", 437),
        ("a high-quality photo of a pelican standing on a subway platform", 144),
        ("a high-quality photo of an aircraft carrier docked inside a canyon", 403),
        ("a high-quality photo of a dishwasher placed on a sidewalk", 534),
        ("a high-quality photo of a sports car parked in a barn", 817),
        ("a high-quality photo of a mountain tent pitched in an airport terminal", 672),
        ("a high-quality photo of a king penguin standing in a classroom", 145),
        ("a high-quality photo of a jeep parked in the center of a library", 609),
        ("a high-quality photo of a gorilla sitting at an office desk", 366),
        ("a high-quality photo of a red panda sitting on a supermarket shelf", 387),
        ("a high-quality photo of a toucan perched on a bathroom mirror", 96),
        ("a high-quality photo of a monarch butterfly resting on a computer keyboard", 323),
        ("a high-quality photo of a church standing in a dense jungle", 497),
        ("a high-quality photo of a palace courtyard inside a cave", 698),
        ("a high-quality photo of a refrigerator standing in a meadow", 760),
        ("a high-quality photo of a limousine driving through a snowy forest", 627),
        ("a high-quality photo of a fountain in the middle of a bedroom", 562),
        ("a high-quality photo of an anemone fish swimming in a roadside puddle", 393),
        ("a high-quality photo of a pelican standing in a basketball gym", 144),
        ("a high-quality photo of a golden retriever sitting in a rowboat indoors", 207),
    ],
}
